on:
  pull_request:
  merge_group:
  # allows manual triggering
  workflow_dispatch:

name: cortex-m on-target tests

jobs:

  hil-qemu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7m-none-eabi
      - name: Build testsuite
        env:
          RUSTFLAGS: -C link-arg=-Tlink.x -D warnings
        run: cargo build -p testsuite --target thumbv7m-none-eabi
      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install qemu-system-arm
      - name: Run testsuite
        run: |
          qemu-system-arm \
            -cpu cortex-m3 \
            -machine lm3s6965evb \
            -nographic \
            -semihosting-config enable=on,target=native \
            -kernel target/thumbv7m-none-eabi/debug/testsuite
